settings:
  map:
    icons:
      router:
        normal:
          'icons/network/router/router-32x32.png': 0 - 0.25, 4
          'icons/network/router/router-64x64.png': 0.25 - 0.5, 2
          'icons/network/router/router-96x96.png': 0.5 - 0.75, 1.5
          'icons/network/router/router-128x128.png': 0.75 - 5, 1
        selected:
          'icons/network/router/router.selected-32x32.png': 0 - 0.25, 4
          'icons/network/router/router.selected-64x64.png': 0.25 - 0.5, 2
          'icons/network/router/router.selected-96x96.png': 0.5 - 0.75, 1.5
          'icons/network/router/router.selected-128x128.png': 0.75 - 5, 1
